kind: pipeline
type: kubernetes
name: test

trigger:
  event: [push]

steps:
  - name: frontend
    image: node:16.15.1-alpine3.16
    commands:
      - cd frontend
      - yarn install --pure-lockfile
      - yarn lint
    depends_on: [clone]

  - name: backend
    image: node:16.15.1-alpine3.16
    commands:
      - cd backend
      - yarn install --pure-lockfile
      - yarn lint
      - yarn test
    depends_on: [clone]
---
kind: pipeline
type: kubernetes
name: build

trigger:
  event: [push]
  branch: [master]

steps:
  - name: builder
    image: plugins/docker
    settings:
      target: builder
      username: { from_secret: quay_username }
      password: { from_secret: quay_password }
      registry: quay.io
      repo: quay.io/zebbra/timetracker
      tags: builder
      cache_from:
        - quay.io/zebbra/timetracker:builder
      mtu: 1300

  - name: release
    image: plugins/docker
    settings:
      username: { from_secret: quay_username }
      password: { from_secret: quay_password }
      registry: quay.io
      repo: quay.io/zebbra/timetracker
      tags: "latest,git-${DRONE_COMMIT_SHA:0:7}"
      cache_from:
        - quay.io/zebbra/timetracker:builder
        - quay.io/zebbra/timetracker:latest
      mtu: 1300
---
kind: pipeline
type: kubernetes
name: deploy

depends_on:
  - test
  - build

trigger:
  event: [push]
  branch: [master]

steps:
  - name: production
    image: pelotech/drone-helm3
    settings:
      kube_api_server: https://kubernetes.default
      kube_token: { from_secret: kubernetes_token }
      kube_certificate: { from_secret: kubernetes_certificate }
      chart: ./deploy/helm
      release: timetracker
      namespace: medi
      values: image.tag=git-${DRONE_COMMIT_SHA:0:7}
      values_files: [deploy/production.yaml]
      reuse_values: false
